#!/usr/bin/env bash

orig_file="$1"       ; shift
expected_output="$1" ; shift
tangle_code="$1"     ; shift

pandoc_command="pandoc --from markdown --to tangle.lua"
[[ ! -z "$tangle_code" ]] && pandoc_command="$pandoc_command --metadata=code:$tangle_code"

(   tmp_output="$(mktemp $orig_file.XXXXXX)"
    trap "rm -rf $tmp_output" INT TERM EXIT
    $pandoc_command "$orig_file" > "$tmp_output"
    diff -B "$expected_output" "$tmp_output" || exit "$?"
)
