#!/usr/bin/env zsh

stack exec -- pandoc-tangle markdown -- code example -- pandoc markdown -- Tangle.md > README.md
stack exec -- pandoc-tangle markdown -- code main    -- code haskell    -- Tangle.md > src/Main.hs
stack exec -- pandoc-tangle markdown -- code lib     -- code haskell    -- Tangle.md > src/Text/Pandoc/Tangle.hs
